<a href="https://colab.research.google.com/github/ThanikPimpiban/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import numpy as np

**Numpy Array**

สร้าง Numpy Array

In [72]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [73]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np_a.shape

(2, 3)

In [75]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [76]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [77]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง Matrix เริ่มต้น (Zeros,one)

In [78]:
np_z = np.zeros((4,5))

In [79]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [81]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random 

In [82]:
np_random = np.random.randn(5,5)
np_random

array([[ 0.15671756,  0.52596829, -0.48763486, -0.91477478, -1.68968369],
       [ 0.44831743, -0.2360582 , -1.11398357, -1.12264987,  0.6215286 ],
       [ 2.00560914, -1.08014375,  1.32498067, -0.49003507, -0.54665463],
       [-0.03516158, -0.53850725,  0.51169228, -1.31183251, -1.83314292],
       [ 0.18093149, -1.16441158,  0.42852992, -0.23838034, -0.73074158]])

In [83]:
2 + (5*np.random.randn(3,3))

array([[ 3.34974365, -4.97456998,  4.37532498],
       [ 5.51296481, -2.97710699,  0.37875586],
       [ 1.34305699,  8.85489253,  1.98438865]])

**random(int)**

In [84]:
np.random.randint(5,11,(4,5))

array([[ 5,  5,  6,  7,  9],
       [ 6,  6,  9, 10,  8],
       [ 9,  6, 10,  5,  5],
       [10,  9,  8, 10,  5]])

In [85]:
1+np_a.T

array([[2, 5],
       [3, 6],
       [4, 7]])

In [86]:
2*np_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [87]:
np_c = np.array([[6,5,4],[3,2,1]])

In [88]:
np_a+np_c

array([[7, 7, 7],
       [7, 7, 7]])

In [89]:
np_a[[1],[1]]

array([5])

In [90]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [91]:
np_a[0,:]

array([1, 2, 3])

## Useful functions

In [92]:
np.sum(np_a)

21

In [93]:
np.sum(np_a,axis=0)

array([5, 7, 9])

In [94]:
np.sum(np_a,axis=1)

array([ 6, 15])

In [95]:
np.mean(np_a,axis=0)

array([2.5, 3.5, 4.5])

## วนลูปเอง

## Summation

In [96]:
np_a.shape

(2, 3)

**np.sum(np_a)**

In [97]:
sum_all =0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all =sum_all + np_a[row,col]
        print(f'we are aat now = {row} , col = {col} , np_a[{row},{col}] , sum_all = {sum_all}')

we are aat now = 0 , col = 0 , np_a[0,0] , sum_all = 1
we are aat now = 0 , col = 1 , np_a[0,1] , sum_all = 3
we are aat now = 0 , col = 2 , np_a[0,2] , sum_all = 6
we are aat now = 1 , col = 0 , np_a[1,0] , sum_all = 10
we are aat now = 1 , col = 1 , np_a[1,1] , sum_all = 15
we are aat now = 1 , col = 2 , np_a[1,2] , sum_all = 21


In [98]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

**np.sum(np_a,axis=0)**

In [99]:
sum_all = np.zeros(np_a.shape[1])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] =sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


In [100]:
sum_all = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] =sum_all[row] + np_a[row,col]
print(sum_all)

[ 6. 15.]


## Quiz กลุ่ม

วนลูปหาค่า
* np.sum(np_a,axis=1)
* np.mean(np_a)
* np.mean(np_a,axis=0)
* np.mean(np_a,axis=1)

In [101]:
sum_all = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] =sum_all[row] + np_a[row,col]
        print(f'we are at now = {row} , col = {col} , np_a[{row},{col}] , sum_all = {sum_all}')
print(sum_all)

we are at now = 0 , col = 0 , np_a[0,0] , sum_all = [1. 0.]
we are at now = 0 , col = 1 , np_a[0,1] , sum_all = [3. 0.]
we are at now = 0 , col = 2 , np_a[0,2] , sum_all = [6. 0.]
we are at now = 1 , col = 0 , np_a[1,0] , sum_all = [6. 4.]
we are at now = 1 , col = 1 , np_a[1,1] , sum_all = [6. 9.]
we are at now = 1 , col = 2 , np_a[1,2] , sum_all = [ 6. 15.]
[ 6. 15.]


In [102]:
np.sum(np_a,axis=1)

array([ 6, 15])

**ข้อ 5**

np.max(np_a)

In [103]:
max_a = 0


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if max_a >= 0:
            max_a = np_a[row,col]
print(max_a)

6


In [104]:
np.max(np_a)

6

**ข้อ 6**

In [119]:
max_a0 = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if max_a0[col] >= 1:
            max_a0[col] = np_a[row,col]
print(max_a0)

[0. 0. 0.]


In [117]:
np.max(np_a,axis=0)

array([4, 5, 6])

**ข้อ 7**

In [125]:
max_a1 = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if max_a1[row] >= 1:
            max_a1[row] = np_a[row,col]
print(max_a1)

[0. 0.]


In [122]:
np.max(np_a,axis=1)

array([3, 6])

**ข้อ 8**

In [111]:
min_a = 0


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if min_a <= 0:
            min_a = np_a[row,col]
print(min_a)

1


In [110]:
np.min(np_a)

1

**ข้อ 9**

In [108]:
min_a0 = np.zeros(np_a.shape[1])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if min_a0[col] <= 0:
            min_a0[col] = np_a[row,col]
print(min_a0)

[1. 2. 3.]


In [109]:
np.min(np_a,axis=0)

array([1, 2, 3])

**ข้อ 10**

In [107]:
min_a1 = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if min_a1[row] <= 0:
            min_a1[row] = np_a[row,col]
print(min_a1)

[1. 4.]


In [106]:
np.min(np_a,axis=1)

array([1, 4])

**Distance Matrix**

In [126]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
from matplotlib import pyplot as plt
plt.scatter(data1[:,0],data1[:,1])

**Euclidean Distance (L2-norm)**

$\sqrt{(x_1-x_2)^2+(y_1-y_2)^2}$

In [ ]:
dist_p1_p2 = np.sqrt(np.power(data1[0,0]-data1[1,0],2) + np.power(data1[0,1]-data1[1,1],2))
dist_p1_p2

In [ ]:
dist_p1_p2 = np.power(np.power(data1[0,0]-data1[1,0],2) + np.power(data1[0,1]-data1[1,1],2),0.5)
dist_p1_p2

In [ ]:
dist_p2_p4 = np.sqrt(np.power(data1[1,0]-data1[3,0],2) + np.power(data1[1,1]-data1[3,1],2))
dist_p2_p4

**Distance function**

In [ ]:
def dist_l2_2(p1,p2):
    return np.sqrt(np.power(p1[0]-p2[0],2) + np.power(p1[1]-p2[1],2))

In [ ]:
dist_l2_2(data1[0,:],data1[1,:])

In [ ]:
dist_l2_2(data1[1,:],data1[3,:])

In [ ]:
def dist_l2_n(p1,p2):
    sum = 0
    for i in range(len(p1)):
        sum = sum + np.power(p1[i]-p2[i],2)
    return np.sqrt(sum)

In [ ]:
dist_l2_n(data1[0,:],data1[1,:])

**Manhattan Distance (L1-norm)**

$|x_1-x_2|+|y_1-y_2|$

**quiz6**

เขียน function คำนวณ manhattan distance ของ ข้อมูล 2 dimensions

**HW11**

* Function คำนวณ manhattan distance ของ ข้อมูล N dimensions
* Function คำนวณ L-$\infty$ ของ ข้อมูล N dimensions
* Function คำนวณ Distance Matrix ด้วย Euclidean Distance