<a href="https://colab.research.google.com/github/ThanikPimpiban/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Numpy Array**

สร้าง Numpy Array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [6]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง Matrix เริ่มต้น (Zeros,one)

In [8]:
np_z = np.zeros((4,5))

In [9]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random 

In [16]:
np_random = np.random.randn(5,5)
np_random

array([[-1.46871369,  0.70619925,  1.96235777, -1.16607137,  0.37945684],
       [-0.09790141, -1.38517855, -3.15432987,  0.53694305,  1.50128073],
       [-0.01812898, -1.39707395, -0.20504782, -0.88519087,  0.42291642],
       [ 0.73360544,  1.15323242,  0.73101985, -1.99147609,  0.94505692],
       [-1.29925337, -0.05796165,  0.64183899, -0.88851148,  0.02302089]])

In [17]:
2 + (5*np.random.randn(3,3))

array([[ 7.07431416, -2.91951309, -2.9709629 ],
       [ 7.3212065 ,  8.89256821,  6.48652982],
       [-0.38899577, -5.38511572, -8.26327121]])

**random(int)**

In [19]:
np.random.randint(5,11,(4,5))

array([[ 8,  5,  5,  5, 10],
       [ 9,  7,  5,  5, 10],
       [10,  5,  6,  8,  6],
       [10, 10,  9,  8,  6]])