<a href="https://colab.research.google.com/github/ThanikPimpiban/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Numpy Array**

สร้าง Numpy Array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])  #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])

In [6]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง Matrix เริ่มต้น (Zeros,one)

In [8]:
np_z = np.zeros((4,5))

In [9]:
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random 

In [12]:
np_random = np.random.randn(5,5)
np_random

array([[-0.74382583, -2.50429284,  1.24219793, -0.32686378, -0.85684858],
       [ 0.56535719,  1.14390445,  1.83875569,  0.42537149,  1.44380549],
       [-1.29902728, -0.52498863,  0.35944085, -0.88441897, -0.56396257],
       [ 0.88939963, -0.06585945, -1.72184597, -1.75034417,  0.97986162],
       [ 1.0983874 , -0.29933486,  0.18420164, -0.44744949,  0.23053577]])

In [13]:
2 + (5*np.random.randn(3,3))

array([[11.702204  , -0.19873454,  3.19941468],
       [ 3.92744227, -6.25191826, -0.45675553],
       [ 2.07008353,  8.59439043,  1.41024925]])

**random(int)**

In [14]:
np.random.randint(5,11,(4,5))

array([[ 7,  5,  6, 10,  9],
       [ 8,  5,  5,  8,  6],
       [ 7,  9,  8,  6,  5],
       [10,  9,  7,  8,  6]])

In [15]:
1+np_a.T

array([[2, 5],
       [3, 6],
       [4, 7]])

In [16]:
2*np_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
np_c = np.array([[6,5,4],[3,2,1]])

In [18]:
np_a+np_c

array([[7, 7, 7],
       [7, 7, 7]])

In [23]:
np_a[[1],[1]]

array([5])

In [24]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [25]:
np_a[0,:]

array([1, 2, 3])

## Useful functions

In [26]:
np.sum(np_a)

21

In [27]:
np.sum(np_a,axis=0)

array([5, 7, 9])

In [28]:
np.sum(np_a,axis=1)

array([ 6, 15])

In [34]:
np.mean(np_a,axis=0)

array([2.5, 3.5, 4.5])

## วนลูปเอง

## Summation

In [35]:
np_a.shape

(2, 3)

**np.sum(np_a)**

In [36]:
sum_all =0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all =sum_all + np_a[row,col]
        print(f'we are aat now = {row} , col = {col} , np_a[{row},{col}] , sum_all = {sum_all}')

we are aat now = 0 , col = 0 , np_a[0,0] , sum_all = 1
we are aat now = 0 , col = 1 , np_a[0,1] , sum_all = 3
we are aat now = 0 , col = 2 , np_a[0,2] , sum_all = 6
we are aat now = 1 , col = 0 , np_a[1,0] , sum_all = 10
we are aat now = 1 , col = 1 , np_a[1,1] , sum_all = 15
we are aat now = 1 , col = 2 , np_a[1,2] , sum_all = 21


In [37]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

**np.sum(np_a,axis=0)**

In [40]:
sum_all = np.zeros(np_a.shape[1])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] =sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


In [41]:
sum_all = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] =sum_all[row] + np_a[row,col]
print(sum_all)

[ 6. 15.]


## Quiz กลุ่ม

วนลูปหาค่า
* np.sum(np_a,axis=1)
* np.mean(np_a)
* np.mean(np_a,axis=0)
* np.mean(np_a,axis=1)

In [44]:
sum_all = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] =sum_all[row] + np_a[row,col]
        print(f'we are at now = {row} , col = {col} , np_a[{row},{col}] , sum_all = {sum_all}')
print(sum_all)

we are at now = 0 , col = 0 , np_a[0,0] , sum_all = [1. 0.]
we are at now = 0 , col = 1 , np_a[0,1] , sum_all = [3. 0.]
we are at now = 0 , col = 2 , np_a[0,2] , sum_all = [6. 0.]
we are at now = 1 , col = 0 , np_a[1,0] , sum_all = [6. 4.]
we are at now = 1 , col = 1 , np_a[1,1] , sum_all = [6. 9.]
we are at now = 1 , col = 2 , np_a[1,2] , sum_all = [ 6. 15.]
[ 6. 15.]


In [43]:
np.sum(np_a,axis=1)

array([ 6, 15])

**ข้อ 5**

np.max(np_a)

In [75]:
max_a = 0


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if max_a >= 0:
            max_a = np_a[row,col]
print(max_a)

6


In [67]:
np.max(np_a)

6

**ข้อ 6**

In [117]:
max_a0 = np.zeros(np_a.shape[1])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if max_a[col] >= 1:
            max_a0[col] = np_a[row,col]
print(max_a0)

[4. 5. 6.]


In [115]:
np.max(np_a,axis=0)

array([4, 5, 6])

**ข้อ 7**

In [116]:
max_a1 = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if max_a[col] >= 1:
            max_a1[row] = np_a[row,col]
print(max_a1)

[3. 6.]


In [84]:
np.max(np_a,axis=1)

array([3, 6])

**ข้อ 8**

In [87]:
min_a = 0


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if min_a <= 0:
            min_a = np_a[row,col]
print(min_a)

1


In [88]:
np.min(np_a)

1

**ข้อ 9**

In [107]:
min_a0 = np.zeros(np_a.shape[1])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if min_a0[col] <= 0:
            min_a0[col] = np_a[row,col]
print(min_a0)

[1. 2. 3.]


In [101]:
np.min(np_a,axis=0)

array([1, 2, 3])

**ข้อ 10**

In [111]:
min_a1 = np.zeros(np_a.shape[0])


for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if min_a1[row] <= 0:
            min_a1[row] = np_a[row,col]
print(min_a1)

[1. 4.]


In [112]:
np.min(np_a,axis=1)

array([1, 4])